### ISSUE TITLE
Exercise 4, Subtask 2 Log Analytics Timing

### ISSUE THREAD

**Issue by tjsullivan1** [CloudLabsAI-Azure/AIW-Cloud-Adoption-Framework#10]
We mention for some of the earlier exercises that certain steps will take X amount of time. The Log Analytics file tracking took a while before I started getting data re: file changes. It was more than 5 minutes, less than an hour, but I don't have a specific value. I would recommend we give a proposed range so individuals going through this lab don't think they have done something wrong.

**Comment by srushti-714** [comment]
Added instructions to specify the required time to get the output for Exercise 4  sub task 2 (step 14).
