### ISSUE TITLE
Exercise 2 Step 14: Prepopulated name does not match documentation for Assignment Name

### ISSUE THREAD

**Issue by dalawlor** [CloudLabsAI-Azure/AIW-Cloud-Adoption-Framework#11]

**Comment by moodaddy** [comment]
Same issue for me, did not however impact ability to complete the lab, but I was expecting an error when I first deployed.

**Comment by srushti-714** [comment]
Thanks for reporting the issue.
The name is updated, please check the commit made referencing this issue.
