### ISSUE TITLE
Documentation - clarity, typos

### ISSUE THREAD

**Issue by moodaddy** [CloudLabsAI-Azure/AIW-Cloud-Adoption-Framework#12]
When specifying the Deployment ID in the name - TWTDeploymentID might be better TWT<deploymentID> with a comment to see the example or the like.  That one snuck past me a bit the first time.  

Exercise 2 2nd paragraph "CAF Migration landing zone implementation option doesn’t implement any governance toolin" is missing a "g" and the next sentence needs a space after the.

On the Deploy to Azure buttons - make the following phrase more attention grabbing - I knew what I was doing so I caught that it wanted me to logging to my own sub, customers will not catch that and the risk of them deploying to their own subs with locked resources is high.

**Comment by srushti-714** [comment]
Changes are done.Please check the commits referring this issue
