### ISSUE TITLE
Lab 1, Step 7, NOTE - Slight Misinformation

### ISSUE THREAD

**Issue by juancvegaMS** [CloudLabsAI-Azure/AIW-Cloud-Adoption-Framework#16]
On Lab 1, Step 7, "Save Draft" - it states in the note section, "Note: You need to click on Save Draft more than two to three times to save the blueprint definition."

This is not accurate.  I tested this a couple of times, and you can click ONCE - give it approximately 10 seconds or so and the Blueprint Definition saves.  If you click two or three times in haste, you will notice that you actually get a notification for each time you clicked save (2 to 3 notifications).  This could lead to failures due to multiple clicks.  I would recommend that you modify the text to read, "Click save and allow approximately 10 seconds for the Blueprint Definition to be saved."

**Comment by srushti-714** [comment]
Updated the instructions: [https://github.com/CloudLabsAI-Azure/AIW-Cloud-Adoption-Framework/commit/13c414f313c897e2ecdbfbda0d2e4f1af7061964](url)
