### ISSUE TITLE
Lab 1, Step 8, Note Clarification

### ISSUE THREAD

**Issue by juancvegaMS** [CloudLabsAI-Azure/AIW-Cloud-Adoption-Framework#17]
In Lab 1, Step 8, Note - it states, "Change the definition location to the subscription L1-MigrationLZ Sub-Suffix if it is set to a different subscription"

This prompted me to work on changing something that was already correctly selected.  My recommendation would be to modify the text to read, 
"**Verify that** the definition location is set to the subscription L1-MigrationLZ Sub-Suffix. If it is not, edit the Blueprint Definition and set it to L1-MigrationLZ Sub-Suffix subscription before continuing."

**Comment by srushti-714** [comment]
Updated the instruction.
