### ISSUE TITLE
Lab 1, Step 11 - Reword the phrase

### ISSUE THREAD

**Issue by juancvegaMS** [CloudLabsAI-Azure/AIW-Cloud-Adoption-Framework#18]
The current phrasing on Lab 1, Step 11 - reads as, "Once the copy of the blueprint sample has been successfully published it can be assigned to a subscription it was saved to."

Correct this to read:  "The Blueprint sample copy is ready to be assigned to the subscription to which it is saved once it is published."

**Comment by srushti-714** [comment]
Updated the instruction
