### ISSUE TITLE
Lab 1, Step 14, 2nd part of the "Subscription" phrasing

### ISSUE THREAD

**Issue by juancvegaMS** [CloudLabsAI-Azure/AIW-Cloud-Adoption-Framework#19]
Currently, on Lab 1, Step 14, for the "Subscription:" prompt, the 2nd part of the phrase reads, "This subscription is where your copy of the blueprint sample is saved to"

Restate this as:  "This value reflects the Subscription where your Blueprint copy is saved"

**Comment by srushti-714** [comment]
Changes are made, please check the commit above.
