### ISSUE TITLE
No Lab Environment Procured on initial Login

### ISSUE THREAD

**Issue by juancvegaMS** [CloudLabsAI-Azure/AIW-Cloud-Adoption-Framework#2]
- I logged onto the Lab Environment but I do not see the JumpVM as the instructions are stating

1. Clicked the Refresh button - no records found
2. Clicked the Lab button - no changes
3. Toggled between the Environment Details and Virtual Machines buttons, I can see the credentials, however, no lab environment is showing.

![image](https://user-images.githubusercontent.com/56441954/98564776-ca47f500-227a-11eb-973a-05c77b61cfc0.png)

**Comment by srushti-714** [comment]
It is temporary issue ,it was fixed later by the resetting the environment.
