### ISSUE TITLE
"Protect Your Account" Warning

### ISSUE THREAD

**Issue by tjsullivan1** [CloudLabsAI-Azure/AIW-Cloud-Adoption-Framework#3]
When logging into the Azure Portal with the provided credentials, I get a warning that I need to protect my account within four days. Likely, this is because the account has owner and we can't eliminate this warning, but I wanted to bring it up just in case.

**Comment by srushti-714** [comment]
Thanks for reporting it , I have added a screenshot and added an instruction for clarification.
