### ISSUE TITLE
Exercise 1, Task 2, Step 16 Blueprint Subnet Deployment Issue

### ISSUE THREAD

**Issue by tjsullivan1** [CloudLabsAI-Azure/AIW-Cloud-Adoption-Framework#5]
In task 2, the blueprint deploys a subnet called Bastion, but we discuss Azure Bastion. If we plan to use for Azure Bastion, we need the subnet to be called AzureBastionSubnet: https://docs.microsoft.com/en-us/azure/bastion/tutorial-create-host-portal#:~:text=The%20subnet%20must%20be%20named%20AzureBastionSubnet.

**Comment by srushti-714** [comment]
Renamed the Bastion subnet to AzureBastionSubnet in the ARM template .
