### ISSUE TITLE
Exercise 1, Task 2 Route Table Clarity

### ISSUE THREAD

**Issue by tjsullivan1** [CloudLabsAI-Azure/AIW-Cloud-Adoption-Framework#6]
The way the lab reads, I expected route tables to be deployed with my VNet. They were not, so it might be worth clarifying.

**Comment by srushti-714** [comment]
@tjsullivan1 Can you please tell the exact step where the route table is mentioned.

**Comment by srushti-714** [comment]
Thanks for the suggestion, we have added a note to clarify the deployment of route tables
