### ISSUE TITLE
Exercise 4, Task 2, Step 6

### ISSUE THREAD

**Issue by tjsullivan1** [CloudLabsAI-Azure/AIW-Cloud-Adoption-Framework#9]
Connect-AzAccount doesn't work for me in cloud shell, but as far as I know this also shouldn't be needed since you are already connected when you launch cloud shell.

**Comment by dalawlor** [comment]
Got the Same issue Error:

WARNING: Unable to acquire token for tenant 'organizations'
Connect-AzAccount: InteractiveBrowserCredential authentication failed: Unable to open a web page using xdg-open. See inner exception for details. Possible causes for this error are: xdg-open is not installed or it cannot find a way to open an url - make sure you can open a web page by invoking from a terminal: xdg-open https://www.bing.com

**Comment by srushti-714** [comment]
@tjsullivan1 @dalawlor  The command is now removed, thanks for reporting it
